language: bash
before_install:
- sudo apt-get install texlive texlive-xetex texlive-math-extra texlive-latex-recommended
  texlive-latex-extra
- wget https://github.com/jgm/pandoc/releases/download/2.6/pandoc-2.6-linux.tar.gz
- tar xvfz pandoc-2.6-linux.tar.gz
script:
- bash deploy.sh
after_success:
- bash push.sh
env:
  global:
    secure: GZRVLrYf8EYMjhk0vzU1bdDF7LcmWzAQeCMZWgjUz58pkIZBH4raBBUGhq9hW+KljonEoSNdNTH5pHZq198Xumoz2aAVKkUDvJp1m1Y4JbJUoHnqMuskKDMvjpRiMgXVbqi2j8LvrgIC6nzmfFzmBd6pAuMjdARkewikQlNcFwOWXDxODbbJS3wSs7WgRJXIHSeLdMKagnxNiBRfiPGG5/tlSmdyALNcHmsaEsnSphicoHBpptT5BIA0aQOa1+idtrMyxZMqwzUTTkJghp1Khcf7yID6V4hy+VhUPhqBFYgkzlf+zTmaOldG4rWKZgXK/0SKs8cU3zt/61jIsevziDemlDXHgrJgy3HszNexs7gbAdK8FpNSmo1dhGjLDh6SWlF6ulKcj+rQhL3+HE6Av1Sux+Nk/s3nwzy4dlyFpTLdSD1HJ0nH6QfRYUz2Vf9/LkVFREOl/21qualAaBpHscP+Wn9Z4emXH0luAOF5qV19p+dvfDbzQzRrKR48UAZSIIzdxnotVue0AYobUGgCA8L6mwGOAp75cDPnUcw4M4CEuBxnYwdvKAIWFqagf4fzbPexGB8/0QLsS8KcZicmNYIg6h6Z4lKG03dba8NWvarOKG+8c0/CG5leNeGcK0wB/uGhY1wlSUjdaGBendb+FOf9b4TQOXkqjmFAkERutvo=
